-- 1. Work Logs Table
create table if not exists public.work_logs (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "workDate" date not null,
  content text,
  attachment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Storage Bucket for Work Log Images
insert into storage.buckets (id, name, public) 
values ('work-log-images', 'work-log-images', true)
on conflict (id) do nothing;

-- 3. RLS Policies (Public Access for Demo)
create policy "Public Select work-log-images"
on storage.objects for select
using ( bucket_id = 'work-log-images' );

create policy "Public Insert work-log-images"
on storage.objects for insert
with check ( bucket_id = 'work-log-images' );

create policy "Public Update work-log-images"
on storage.objects for update
using ( bucket_id = 'work-log-images' );

create policy "Public Delete work-log-images"
on storage.objects for delete
using ( bucket_id = 'work-log-images' );