-- Fire History Table (화재 이력 관리)
create table if not exists public.fire_history (
  id bigint generated by default as identity primary key,
  "marketName" text,
  "receiverMac" text,
  "receiverStatus" text, -- 공통코드 (예: '10', '35')
  "repeaterId" text,
  "repeaterStatus" text, -- 공통코드 (예: '35', '49')
  "detectorInfoChamber" text, -- 감지기ID_챔버
  "detectorInfoTemp" text, -- 감지기ID_온도
  registrar text default 'system', -- 등록자
  "registeredAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "falseAlarmStatus" text default '등록', -- 오탐여부 (등록, 화재, 오탐)
  note text, -- 비고
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.fire_history enable row level security;

create policy "Public Select fire_history" on public.fire_history for select using ( true );
create policy "Public Insert fire_history" on public.fire_history for insert with check ( true );
create policy "Public Update fire_history" on public.fire_history for update using ( true );
create policy "Public Delete fire_history" on public.fire_history for delete using ( true );

-- Initial Data (Screenshot Mock Data)
INSERT INTO public.fire_history ("marketName", "receiverMac", "receiverStatus", "repeaterId", "repeaterStatus", "detectorInfoChamber", "detectorInfoTemp", registrar, "registeredAt", "falseAlarmStatus") VALUES
('삼성중공업', '01A4', '10', '06', '35', '07(ITR2)', null, 'system', '2025-12-24 16:15:53', '등록'),
('호계종합시장', '0193', '10', '01', '35', '10(그린야채)', null, 'system', '2025-12-24 14:29:45', '등록'),
('송강시장', '0707', '49', '07', '49', null, null, 'system', '2025-12-24 05:15:01', '등록'),
('공릉동도깨비시장', '015F', '10', '05', '35', '04(설악코너)', null, 'system', '2025-12-23 17:55:32', '등록'),
('공릉동도깨비시장', '015F', '10', '05', '35', '04(설악코너)', null, 'system', '2025-12-23 17:55:30', '등록'),
('공릉동도깨비시장', '015F', '10', '05', '35', '04(설악코너)', null, 'system', '2025-12-23 17:55:21', '등록'),
('비단길현대시장', '01AB', '49', '01', '49', null, null, 'system', '2025-12-23 13:37:58', '등록'),
('비단길현대시장', '01AB', '14', '01', '35', null, '01(상인회사무실', 'system', '2025-12-23 13:37:36', '등록'),
('비단길현대시장', '01AB', '14', '01', '35', null, '01(상인회사무실', 'system', '2025-12-23 13:37:34', '등록'),
('비단길현대시장', '01AB', '14', '01', '35', null, '01(상인회사무실', 'system', '2025-12-23 13:37:23', '등록');
