-- Transmitters Table (발신기 관리)
-- 기존 테이블 삭제 (컬럼명 변경 및 정책 충돌 방지)
DROP TABLE IF EXISTS public.transmitters;

create table public.transmitters (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "transmitterId" text not null, -- '01' ~ '20'
  status text default '사용', -- usageStatus -> status 변경
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.transmitters enable row level security;

create policy "Public Select transmitters" on public.transmitters for select using ( true );
create policy "Public Insert transmitters" on public.transmitters for insert with check ( true );
create policy "Public Update transmitters" on public.transmitters for update using ( true );
create policy "Public Delete transmitters" on public.transmitters for delete using ( true );
