-- Menus Table (기존 테이블 구조 유지)
create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  "parentId" bigint references public.menus(id),
  label text not null,
  path text,
  icon text,
  "sortOrder" int default 0,
  "isVisiblePc" boolean default true,
  "isVisibleMobile" boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (기존 유지)
alter table public.menus enable row level security;

create policy "Public Select menus" on public.menus for select using ( true );
create policy "Public Update menus" on public.menus for update using ( true );
create policy "Public Insert menus" on public.menus for insert with check ( true );
create policy "Public Delete menus" on public.menus for delete using ( true );

-- [중요] 기존 데이터 초기화 (사이트맵 동기화를 위해)
truncate table public.menus restart identity cascade;

-- Seed Data (현재 사이트맵 기준 재설정)

-- 1. Dashboard (최상위)
insert into public.menus (label, path, icon, "sortOrder", "isVisiblePc", "isVisibleMobile")
values ('대시보드', '/dashboard', 'Home', 10, true, true);

-- 2. System Management (폴더)
insert into public.menus (label, path, icon, "sortOrder", "isVisiblePc", "isVisibleMobile")
values ('시스템 관리', null, 'Settings', 20, true, false); 

-- 2-1. System Children
do $$
declare
  parent_id bigint;
begin
  select id into parent_id from public.menus where label = '시스템 관리';
  
  insert into public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile") values
  (parent_id, '사용자 관리', '/users', 10, true, false),
  (parent_id, '총판 관리', '/distributors', 20, true, false),
  (parent_id, '시장 관리', '/markets', 30, true, false),
  (parent_id, '상가 관리', '/stores', 40, true, false),
  (parent_id, '문자 전송', '/sms', 50, true, false),
  (parent_id, '작업일지', '/work-logs', 60, true, true),
  (parent_id, '롤 관리', '/roles', 70, true, false),
  (parent_id, '메뉴 관리', '/menus', 80, true, false), -- 메뉴 관리 추가
  (parent_id, '접속 로그', '/access-logs', 90, true, false);
end $$;

-- 3. Device Management (폴더)
insert into public.menus (label, path, icon, "sortOrder", "isVisiblePc", "isVisibleMobile")
values ('기기 관리', null, 'Cpu', 30, true, false);

-- 3-1. Device Children
do $$
declare
  parent_id bigint;
begin
  select id into parent_id from public.menus where label = '기기 관리';
  
  insert into public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile") values
  (parent_id, 'R형 수신기', '/receivers', 10, true, false),
  (parent_id, '중계기 관리', '/repeaters', 20, true, false),
  (parent_id, '화재감지기', '/detectors', 30, true, false);
end $$;

-- 4. Data Management (폴더)
insert into public.menus (label, path, icon, "sortOrder", "isVisiblePc", "isVisibleMobile")
values ('데이터 관리', null, 'Activity', 40, true, true);

-- 4-1. Data Children
do $$
declare
  parent_id bigint;
begin
  select id into parent_id from public.menus where label = '데이터 관리';
  
  insert into public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile") values
  (parent_id, '화재 이력 관리', '/fire-history', 10, true, true),
  (parent_id, '기기 상태 관리', '/device-status', 20, true, true);
end $$;