-- Receivers Table (R형 수신기 관리)
create table if not exists public.receivers (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "macAddress" text not null,
  ip text,
  dns text,
  "emergencyPhone" text,
  "transmissionInterval" text default '01시간',
  image text,
  status text default '사용',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Bucket for Receiver Images
insert into storage.buckets (id, name, public) 
values ('receiver-images', 'receiver-images', true)
on conflict (id) do nothing;

-- RLS Policies
create policy "Public Select receiver-images"
on storage.objects for select
using ( bucket_id = 'receiver-images' );

create policy "Public Insert receiver-images"
on storage.objects for insert
with check ( bucket_id = 'receiver-images' );

create policy "Public Update receiver-images"
on storage.objects for update
using ( bucket_id = 'receiver-images' );

create policy "Public Delete receiver-images"
on storage.objects for delete
using ( bucket_id = 'receiver-images' );