-- Transmitters Table (발신기 관리)
create table if not exists public.transmitters (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "transmitterId" text not null, -- '01' ~ '20'
  "usageStatus" text default '사용',
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.transmitters enable row level security;

create policy "Public Select transmitters" on public.transmitters for select using ( true );
create policy "Public Insert transmitters" on public.transmitters for insert with check ( true );
create policy "Public Update transmitters" on public.transmitters for update using ( true );
create policy "Public Delete transmitters" on public.transmitters for delete using ( true );

-- Insert Menu Item (발신기 관리)
-- Parent ID 3 is '기기 관리'
INSERT INTO public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile")
VALUES (3, '발신기 관리', '/transmitters', 40, true, false);
