-- Device Status Table (기기 상태 관리)
create table if not exists public.device_status (
  id bigint generated by default as identity primary key,
  "marketName" text,
  "receiverMac" text,
  "repeaterId" text,
  "deviceType" text, -- '수신기', '감지기' 등
  "deviceId" text,
  "deviceStatus" text, -- '정상', '에러' 등
  "errorCode" text, -- 공통코드 (예: '04')
  "registeredAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "processStatus" text default '미처리', -- '처리', '미처리'
  note text, -- 비고
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.device_status enable row level security;

create policy "Public Select device_status" on public.device_status for select using ( true );
create policy "Public Insert device_status" on public.device_status for insert with check ( true );
create policy "Public Update device_status" on public.device_status for update using ( true );
create policy "Public Delete device_status" on public.device_status for delete using ( true );

-- Ensure common code for '04' exists (Communication Error)
INSERT INTO public.common_codes (code, name, description, "groupCode", "groupName", status)
VALUES ('04', '통신이상', '기기 통신 이상 에러', 'ERR_CODE', '에러 코드', '사용')
ON CONFLICT DO NOTHING;

-- Initial Mock Data (Based on screenshot description)
INSERT INTO public.device_status ("marketName", "receiverMac", "repeaterId", "deviceType", "deviceId", "deviceStatus", "errorCode", "registeredAt", "processStatus") VALUES
('관양시장', '0136', '03', '수신기', '01', '에러', '04', '2026-01-13 11:40:03', '미처리'),
('자갈밭시장', '0156', '04', '수신기', '01', '에러', '04', '2026-01-13 11:40:03', '미처리'),
('관양시장', '0136', '01', '수신기', '01', '에러', '04', '2026-01-13 11:40:03', '미처리'),
('관양시장', '0136', '05', '감지기', '09', '정상', null, '2026-01-13 11:38:26', '미처리'),
('관양시장', '0136', '11', '수신기', '01', '에러', '04', '2026-01-13 11:37:20', '미처리'),
('관양시장', '0136', '10', '수신기', '01', '에러', '04', '2026-01-13 11:37:19', '미처리'),
('관양시장', '0136', '08', '수신기', '01', '에러', '04', '2026-01-13 11:37:18', '미처리'),
('관양시장', '0136', '09', '수신기', '01', '에러', '04', '2026-01-13 11:37:18', '미처리'),
('관양시장', '0136', '07', '수신기', '01', '에러', '04', '2026-01-13 11:37:17', '미처리'),
('관양시장', '0136', '06', '수신기', '01', '에러', '04', '2026-01-13 11:37:16', '미처리');