-- Alarms Table (경종 관리)
-- 기존 테이블 삭제 (컬럼명 변경 및 정책 충돌 방지)
DROP TABLE IF EXISTS public.alarms;

create table public.alarms (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "alarmId" text not null, -- '01' ~ '20'
  status text default '사용', -- usageStatus -> status 변경
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.alarms enable row level security;

create policy "Public Select alarms" on public.alarms for select using ( true );
create policy "Public Insert alarms" on public.alarms for insert with check ( true );
create policy "Public Update alarms" on public.alarms for update using ( true );
create policy "Public Delete alarms" on public.alarms for delete using ( true );

-- Insert Menu Item (경종 관리) - 중복 방지를 위해 충돌 시 무시
INSERT INTO public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile")
VALUES (3, '경종 관리', '/alarms', 50, true, false)
ON CONFLICT DO NOTHING;
