-- Detectors Table (화재감지기 관리)
create table if not exists public.detectors (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "storeId" bigint references public.stores(id), -- Nullable (상가가 없을 수도 있음)
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "detectorId" text not null, -- '01' ~ '20'
  mode text default '복합', -- 복합, 열, 연기
  "cctvUrl" text,
  "usageStatus" text default '사용',
  "smsList" text[] default '{}',
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
create policy "Public Select detectors"
on public.detectors for select
using ( true );

create policy "Public Insert detectors"
on public.detectors for insert
with check ( true );

create policy "Public Update detectors"
on public.detectors for update
using ( true );

create policy "Public Delete detectors"
on public.detectors for delete
using ( true );