-- Repeaters Table (중계기 관리)
create table if not exists public.repeaters (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "alarmStatus" text default '사용', -- 경종 사용여부
  location text,
  image text,
  status text default '사용',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Bucket for Repeater Images
insert into storage.buckets (id, name, public) 
values ('repeater-images', 'repeater-images', true)
on conflict (id) do nothing;

-- RLS Policies
create policy "Public Select repeater-images"
on storage.objects for select
using ( bucket_id = 'repeater-images' );

create policy "Public Insert repeater-images"
on storage.objects for insert
with check ( bucket_id = 'repeater-images' );

create policy "Public Update repeater-images"
on storage.objects for update
using ( bucket_id = 'repeater-images' );

create policy "Public Delete repeater-images"
on storage.objects for delete
using ( bucket_id = 'repeater-images' );